import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {

    extend: {
      colors: {
        yt_spec_base_background: "#0f0f0f",
        yt_spec_raised_background: "#212121",
        yt_spec_menu_background: "#282828",
        yt_spec_inverted_background: "#f1f1f1",
        yt_spec_text_primary: "#fff",
        yt_spec_text_secondary: "#aaa",
        yt_spec_text_disabled: "#717171",
        yt_spec_text_primary_inverse: "#030303",
        yt_spec_call_to_action: "#3ea6ff",
        yt_spec_call_to_action_inverse: "#065fd4",
        yt_spec_suggested_action: "#263850",
        yt_spec_suggested_action_inverse: "#def1ff",
        yt_spec_icon_active_other: "#fff",
        yt_spec_icon_inactive: "#909090",
        yt_spec_icon_disabled: "#606060",
        yt_spec_touch_response: "#fff",
        yt_spec_touch_response_inverse: "#000",
        yt_spec_brand_icon_active: "#fff",
        yt_spec_brand_icon_inactive: "#909090",
        yt_spec_brand_link_text: "#ff4e45",
        yt_spec_wordmark_text: "#fff",
        yt_spec_error_indicator: "#ff8983",
        yt_spec_themed_blue: "#3ea6ff",
        yt_spec_themed_green: "#2ba640",
        yt_spec_ad_indicator: "#00aaa7",
        yt_spec_commerce_badge_background: "#002d08",
        yt_spec_static_brand_red: "#f00",
        yt_spec_static_brand_white: "#fff",
        yt_spec_static_brand_black: "#212121",
        yt_spec_static_ad_yellow: "#fbc02d",
        yt_spec_static_grey: "#606060",
        yt_spec_static_overlay_text_primary: "#fff",
        yt_spec_static_overlay_text_primary_inverse: "#030303",
        yt_spec_static_overlay_call_to_action: "#3ea6ff",
        yt_spec_static_overlay_icon_active_other: "#fff",
        yt_spec_static_overlay_touch_response: "#fff",
        yt_spec_static_overlay_touch_response_inverse: "#000",
        yt_spec_assistive_feed_themed_gradient_1: "#005446",
        yt_spec_assistive_feed_themed_gradient_2: "#39003f",
        yt_spec_assistive_feed_themed_gradient_3: "#590000",
        yt_spec_discover_red: "#ff4e45",
        yt_spec_discover_green: "#a4ffa4",
        yt_spec_discover_blue: "#6ea2ff",
        yt_spec_brand_background_solid: "#212121",
        yt_spec_general_background_a: "#181818",
        yt_spec_general_background_b: "#0f0f0f",
        yt_spec_general_background_c: "#030303",
        yt_spec_error_background: "#f9f9f9",
        yt_spec_snackbar_background: "#030303",
        yt_spec_snackbar_background_updated: "#f9f9f9",
        t_spec_brand_button_background: "#c00",
        yt_spec_call_to_action_hover: "#6ebcff",
        yt_spec_brand_button_background_hover: "#990412",
        yt_spec_mono_filled_hover: "#d9d9d9",
        yt_spec_mono_filled_hover_inverse: "#272727",
        yt_spec_commerce_filled_hover: "#65b8ff",
        yt_spec_commerce_tonal_hover: "#515561",
        yt_spec_static_overlay_filled_hover: "#e6e6e6",
        yt_spec_filled_button_text: "#030303",
        yt_spec_selected_nav_text: "#fff",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
    },
  },
  plugins: [],
};
export default config;
